### PR TITLE
Revert "small typo in documentation - download page"

### PR DESCRIPTION
**Pull request by krasserm**
Reverts RBMHTechnology/eventuate#104

### CODE REVIEW

**Comment by krasserm** [comment]
@aconstantin, sorry I had to revert because your patch was for the gh-pages branch. Content on this branch is generated. The sources are at https://github.com/RBMHTechnology/eventuate/tree/master/src/sphinx.

**Comment by krasserm** [comment]
@aconstantin Instructions how to build the documentation locally are at http://rbmhtechnology.github.io/eventuate/developers.html#documentation.

**Comment by krasserm** [comment]
As I'm starting to prepare the 0.3 release now, I'll apply your diff to master myself.

**Comment by aconstantin** [comment]
Oh, I wasn't aware of that and assumed `_sources` would contain the sources.

**Comment by krasserm** [comment]
Yeah, maybe that's misleading. Sphinx creates that directory and the contained files are the *sources* used by the renderer.

**Pull request merged**
